### ISSUE TITLE
Infografía Realidad Aumentada.

### ISSUE THREAD

**Issue by uzias10** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-uzias10#1]
[Infografía RA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-uzias10/files/10844677/Infografia.RA.pdf)

**Comment by carlos-chrs** [comment]
muy bien Hecho. 
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
